name: Build / Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clone tree-sitter-rescript
        run: git clone https://github.com/aspeddro/tree-sitter-rescript.git

      - name: Build
        working-directory: tree-sitter-rescript/
        run: |
          git checkout fix-type-scanner
          yarn install --frozen-lockfile
          yarn tree-sitter generate
          yarn tree-sitter build-wasm
          cp tree-sitter-rescript.wasm ../

      - name: Commit wasm
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): generate wasm"
          file_pattern: tree-sitter-rescript.wasm
